version: "3.8"

name: eventguru
services:

    # Configurazione database
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: dockeruser
            POSTGRES_PASSWORD: dockerpassword
            POSTGRES_DB: dockerdb
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    # Configurazione BE
    be:
        container_name: EventGURU_BE
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - postgres # This service depends on mysql. Start that first.
        environment: # Pass environment variables to the service
            - spring.datasource.url=jdbc:postgresql://postgres:5432/dockerdb
            - spring.datasource.username=dockeruser
            - spring.datasource.password=dockerpassword

    # Configurazione FE
    fe:
        container_name: EventGURU_FE
        depends_on:
            - be
        build:
            context: ../FE
            dockerfile: Dockerfile

    # Configurazione proxy
    proxy-manager:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - /etc/nginx-proxy-manager/data:/data
            - /etc/letsencrypt:/etc/letsencrypt

volumes:
    postgres-data:
