version: "3.8"

name: eventguru
services:

    pgadmin:
        image: dpage/pgadmin4
        container_name: hyre-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: hyre@admin.com
            PGADMIN_DEFAULT_PASSWORD: password
        ports:
            - "5099:80"
        volumes:
            - pgadmin_data:/var/lib/pgadmin

    # Configurazione database
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: dockeruser
            POSTGRES_PASSWORD: dockerpassword
            POSTGRES_DB: dockerdb
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    # Configurazione BE
    be:
        container_name: EventGURU_BE
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - postgres # Start that first.
        environment: # Pass environment variables to the service
            - spring.datasource.url=jdbc:postgresql://postgres:5432/dockerdb
            - spring.datasource.username=dockeruser
            - spring.datasource.password=dockerpassword

    # Configurazione FE
    fe:
        container_name: EventGURU_FE
        depends_on:
            - be
        build:
            context: ../FE
            dockerfile: Dockerfile

    # Configurazione proxy
    proxy-manager:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - /etc/nginx-proxy-manager/data:/data
            - /etc/letsencrypt:/etc/letsencrypt

volumes:
    postgres-data:
    pgadmin_data:
